"""Cross-task semantic memory via finding embeddings in Chroma.

Accepted task findings are chunked and stored in the existing Chroma
instance with kind="finding" metadata. This allows future tasks to
retrieve semantically relevant prior findings via rag.retrieve() with
a metadata filter, without any new vector store.
"""
from __future__ import annotations

import hashlib
import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from rag.hybrid import LiteHybridRAG

logger = logging.getLogger(__name__)


def store_finding(
    text: str,
    task_id: str,
    task_desc: str,
    rag: "LiteHybridRAG",
) -> None:
    """Ingest a finding string into Chroma with kind=finding metadata.

    Uses a content-stable ID so repeated ingestion of the same finding
    is idempotent (existing ID is skipped by Chroma).
    """
    if not text or not text.strip():
        return
    finding_hash = hashlib.md5(f"{task_id}:{text[:120]}".encode()).hexdigest()[:12]
    chunk_id = f"finding::{task_id}::{finding_hash}"
    if chunk_id in rag._ids:
        return
    try:
        rag.add([{
            "id": chunk_id,
            "text": text[:2000],
            "meta": {
                "kind": "finding",
                "task_id": task_id,
                "task": task_desc[:80],
            },
        }])
        logger.debug("[SEMANTIC_MEMORY] Stored finding for task %s", task_id[:8])
    except Exception as exc:
        logger.warning("[SEMANTIC_MEMORY] Failed to store finding: %s", exc)


def recall_prior_findings(
    query: str,
    rag: "LiteHybridRAG",
    k: int = 4,
) -> list[dict]:
    """Return the k most relevant prior findings from all past tasks."""
    try:
        return rag.retrieve(query, k=k, metadata_filters={"kind": "finding"})
    except Exception as exc:
        logger.warning("[SEMANTIC_MEMORY] Recall failed: %s", exc)
        return []


def extract_findings_from_artifact(artifact: dict, task: Any) -> list[str]:
    """Extract a list of finding strings from an accepted artifact.

    Pulls from the narrative generated by roles.generate_narrative():
    key_results, conclusions (split into sentences), and a short
    analysis snippet.
    """
    findings: list[str] = []
    report = artifact.get("report", {})
    narrative = report.get("narrative", {})

    for result in (narrative.get("key_results") or []):
        if isinstance(result, str) and len(result.strip()) > 10:
            findings.append(result.strip())

    conclusions = (narrative.get("conclusions") or "").strip()
    if conclusions:
        sentences = [s.strip() for s in conclusions.split(".") if len(s.strip()) > 20]
        findings.extend(sentences[:3])

    analysis = (narrative.get("analysis") or "").strip()
    if len(analysis) > 50:
        findings.append(f"Analysis [{task.task[:60]}]: {analysis[:400]}")

    return [f for f in findings if f]


def ingest_artifact_findings(
    artifact: dict,
    task: Any,
    rag: "LiteHybridRAG",
) -> int:
    """Extract findings from artifact and store them in semantic memory.

    Returns the number of finding strings stored.
    """
    findings = extract_findings_from_artifact(artifact, task)
    for finding in findings:
        store_finding(finding, task.task_id, task.task, rag)
    if findings:
        logger.info(
            "[SEMANTIC_MEMORY] Stored %d findings from task %s",
            len(findings), task.task_id[:8],
        )
    return len(findings)
